package com.project.common.utils;

public enum Calendar {
	MONDAY_MORNING_1, MONDAY_MORNING_2, MONDAY_AFTERNOON_1, MONDAY_AFTERNOON_2, MONDAY_EVENING_1, MONDAY_EVENING_2,
	TUESDAY_MORNING_1, TUESDAY_MORNING_2, TUESDAY_AFTERNOON_1, TUESDAY_AFTERNOON_2, TUESDAY_EVENING_1,
	TUESDAY_EVENING_2, WEDNESDAY_MORNING_1, WEDNESDAY_MORNING_2, WEDNESDAY_AFTERNOON_1, WEDNESDAY_AFTERNOON_2,
	WEDNESDAY_EVENING_1, WEDNESDAY_EVENING_2, THURSDAY_MORNING_1, THURSDAY_MORNING_2, THURSDAY_AFTERNOON_1,
	THURSDAY_AFTERNOON_2, THURSDAY_EVENING_1, THURSDAY_EVENING_2, FRIDAY_MORNING_1, FRIDAY_MORNING_2,
	FRIDAY_AFTERNOON_1, TFRIDAY_AFTERNOON_2, FRIDAY_EVENING_1, FRIDAY_EVENING_2, SATURDAY_MORNING_1, SATURDAY_MORNING_2,
	SATURDAY_AFTERNOON_1, SATURDAY_AFTERNOON_2, SATURDAY_EVENING_1, SATURDAY_EVENING_2, SUNDAY_MORNING_1,
	SUNDAY_MORNING_2, SUNDAY_AFTERNOON_1, SUNDAY_AFTERNOON_2, SUNDAY_EVENING_1, SUNDAY_EVENING_2
}
