package com.project.common.utils;

public enum PercentageOfMoney {
	FIVE_PERCENT,
	TEN_PERCENT,
	FIFTEEN_PERCENT,
	TWENTY_PERCENT,
	TWENTY_FIVE_PERCENT,
	THIRTY_PERCENT,
	THIRTY_FIVE_PERCENT,
	FORTY_PERCENT,
	FORTY_FIVE_PERCENT,
	FIFTY_PERCENT
}
