package com.project.common.utils;

public enum TaskStatus {
	AVAILABLE_PUBLIC,
	AVAILABLE_UNPUBLIC,
	CLOSED_GO,
	CLOSED_GO_SUCCESS,
	CLOSED_GO_FAIL,
	CLOSED_FAIL,
	CLOSED_GO_SUCCESS_FINISHED,
	CLOSED_GO_FAIL_FINISHED,
	CLOSED_FAIL_FINISHED
}
