server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: "none"
  
spring:
  #Data Configuration  
  datasource:
    #url:  jdbc:postgresql://112.78.1.62/databasecentral jdbc:postgresql://host.docker.internal:49153/giasuomt
    url:   jdbc:postgresql://localhost:5432/OMTDev
    username: postgres
    password: postgres
    #password: khangdeptrai anhhungemkhang48@
  #JPA Configuration 
  jpa:
    show-sql: true #để xem câu sql mà nó tự sinh
    generate-ddl: true #để thằng Hibernate tự nhìn Object và tạo database được
    hibernate: 
      ddl-auto: update
OAuth:            
 client: ws-omt
 secret: cHJvamVjdE9NVFNlY3JldA==
 expired: 50000 # s 
 resource: project-omt-ws