server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: "none"
  
spring:
  #Data Configuration  
  datasource:
    #url:  jdbc:postgresql://112.78.1.62/databasecentral jdbc:postgresql://host.docker.internal:49153/giasuomt
    url:  jdbc:postgresql://localhost:5432/OMTDev
    username: ${USERNAME_POSTGRES}
    password: ${PASSWORD_POSTGRES}
   
    #password: khangdeptrai anhhungemkhang48@
  #JPA Configuration 
  jpa:
    show-sql: true #để xem câu sql mà nó tự sinh
    hibernate: 
      ddl-auto: update